export const bannedCards = [
    //actual banned cards
    "Ancestral Recall",
	"Balance",
	"Biorhythm",
	"Black Lotus",
	"Chaos Orb",
	"Channel",
	"Dockside Extortionist",
	"Emrakul, the Aeons Torn",
	"Erayo, Soratami Ascendant",
	"Falling Star",
	"Fastbond",
	"Flash",
	"Golos, Tireless Pilgrim",
	"Griselbrand",
	"Hullbreacher",
	"Iona, Shield of Emeria",
	"Karakas",
	"Jeweled Lotus",
	"Leovold, Emissary of Trest",
	"Library of Alexandria",
	"Limited Resources",
	"Lutri, the Spellchaser",
	"Mana Crypt",
	"Mox Emerald",
	"Mox Jet",
	"Mox Pearl",
	"Mox Ruby",
	"Mox Sapphire",
	"Nadu, Winged Wisdom",
	"Paradox Engine",
	"Primeval Titan",
	"Prophet of Kruphix",
	"Recurring Nightmare",
	"Rofellos, Llanowar Emissary",
	"Shahrazad",
	"Sundering Titan",
	"Sylvan Primordial",
	"Time Vault",
	"Time Walk",
	"Tinker",
	"Tolarian Academy",
	"Trade Secrets",
	"Upheaval",
	"Yawgmoth's Bargain",
    //conspiracy cards
    "Adriana's Valor",
    "Advantageous Proclamation",
    "Assemble the Rank and Vile",
    "Backup Plan",
    "Brago's Favor",
    "Double Stroke",
    "Echoing Boon",
    "Emissary's Ploy",
    "Hired Heist",
    "Hold the Perimeter",
    "Immediate Action",
    "Iterative Analysis",
    "Muzzio's Preparations",
    "Natural Unity",
    "Power Play",
    "Secrets of Paradise",
    "Sentinel Dispatch",
    "Sovereign's Realm",
    "Summoner's Bond",
    "Unexpected Potential",
    "Weight Advantage",
    "Worldknit",
    "Hymn of the Wilds",
    "Secret Summoning",
    //ante cards:
    "Amulet of Quoz",
    "Bronze Tablet",
    "Contract from Below",
    "Darkpact",
    "Demonic Attorney",
    "Jeweled Bird",
    "Rebirth",
    "Tempest Efreet",
    "Timmerian Fiends"
];